Spring:
  application:
    name: Baidu-MQ-consumer
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB
  rabbitmq:
    host: 119.3.158.9
    port: 5672
    username: usst104
    password: 123456
    virtualHost: /
server:
  tomcat:
    max-swallow-size: 100MB
  port: 8081